### ISSUE TITLE
Patcher Launch

### ISSUE THREAD

**Issue by rosycactuar** [LazyDuchess/AlderLakePatcher#1]
Hi! Sorry if this question has already been asked, but when I try to launch the patcher nothing happens. Do you know why this could be happening and what I could do to fix it?

**Comment by LazyDuchess** [comment]
Hi! No errors or anything? Tried launching as adminitrator, extracted the zip file?

**Comment by rosycactuar** [comment]
Yes, I was opening it as admin and extracted the zip. I even logged in to the hidden admin account and nothing happened.

It doesn't give me an error message or anything, I just try to open it and nothing ever pops up.

**Comment by rosycactuar** [comment]
oh, wait, nevermind. This time it worked. I don't know what happened before, but it launched this time. Thank you!
